Adding image-based invasion percolation algorithm
PMEAL/porespy pull request #341
Opened 2021-01-16 03:00 UTC by jgostick

2021-01-16 04:35 UTC, jgostick commented
The two remain errors are fixed on the gravity packing branch, so will leave until that gets merged into dev

2021-01-17 01:59 UTC, jgostick commented
The coverage for numba functions is not counted.  I added quite a few for the ibip method so it appears like the coverage of the diff is very low.

2021-04-16 22:19 UTC, ma-sadeghi requested changes

2021-04-16 22:19 UTC, ma-sadeghi commented on porespy/filters/__ibip__.py
> +                print('\nNo more accessible invasion sites found...exiting')
We should probably use `loguru`'s "info" instead of `print` statements.

2021-04-16 22:19 UTC, ma-sadeghi commented on porespy/filters/__ibip__.py
> +                print('\nMaximum number of iterations reached...exiting')
This also needs to be `loguru.info`

2021-04-17 22:46 UTC, merged